### ISSUE TITLE
Mismatched transactionID

### ISSUE THREAD

**Issue by sillydong** [AdamSLevy/modbus#2]
Hi, I got lots of Mismatched transactionID when using this lib, and I checked the request and response data, they were all staggerd as the following data:

> 2018/09/04 12:35:18 Tx: 00c500000006020400000002
2018/09/04 12:35:18 Rx Full: 00c400000007020404436395f300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2018/09/04 12:35:18 send: Mismatched transactionID
2018/09/04 12:35:18 Tx: 00c600000006020400080002
2018/09/04 12:35:18 Rx Full: 00c500000007020404436395f300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2018/09/04 12:35:18 send: Mismatched transactionID
2018/09/04 12:35:19 Tx: 00c700000006020400000002
2018/09/04 12:35:19 Rx Full: 00c6000000070204040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2018/09/04 12:35:19 send: Mismatched transactionID
2018/09/04 12:35:19 Tx: 00c800000006020400000002
2018/09/04 12:35:19 Rx Full: 00c70000000702040443638dd100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2018/09/04 12:35:19 send: Mismatched transactionID

Tx is request and Rx is response.

**Comment by AdamSLevy** [comment]
This isn't showing up in my test suite which is tested against an official
Modbus slave implementation (diagslave) so there is something about your
setup that is contributing to this. That doesn't mean that it isn't a bug
with my library but it's not one that my tests can currently reproduce.

First off are you using the latest version of this library without other
modifications?

Also can you point me to the code where you interact with my library? Are
you calling things from multiple goroutines?

**Comment by sillydong** [comment]
I am calling it from multiple goroutines. I set up 8 worker to handle the query job with the same ClientHandle. This usually happen when the modbustcp connection is not always stable. There may be some network fluctuation.

**Comment by AdamSLevy** [comment]
Hmm so it's been awhile since I worked with this library but I think this
is likely the source of your problem. Try using separate ClientHandles per
goroutine. They are pretty lightweight so they shouldn't add much overhead.
They will use the same serial connection but properly serialize your
requests and return them to the correct ClientHandle. If you reuse the
clientHandle from multiple goroutines you may get the mismatched
transaction ID.

Just save the connection settings in some place globally accessible to your
goroutines (or pass it in) and then create a new ClientHandle using the
same connection settings.

I may need to improve the documentation and review my own work.

**Comment by sillydong** [comment]
So use it in multiple gorutines may not be safety. I will try separate the clienthandle.
